### ISSUE TITLE
Eximición

### ISSUE THREAD

**Issue by diegonavarrovergara** [Exploratorio-DCC-PUC/Syllabus-2018-1#103]
Hola, en el criterio de eximición dice que uno se puede eximir con 6,0 y con una nota roja. Mi pregunta es si ese promedio 6,0 se calcula borrando la peor nota o sin borrar la peor nota (tengo un 1,0 en una tarea chica). Gracias.

**Comment by diflores** [comment]
Hola, Diego

La nota de presentación a examen se calcula después de borrar la peor nota según lo que más te convenga (nota de tarea chica o nota de control).
